### ISSUE TITLE
The CDN https://unpkg.com/phosphor-icons not working

### ISSUE THREAD

**Issue by gopikrishna-manifest** [phosphor-icons/homepage#185]
**Describe the bug**
We used the CDN **https://unpkg.com/phosphor-icons** in our Angular application. It works fine up to yesterday. But today, it is it not working. the URL is not working and returning 502. 

**To Reproduce**
1. Add the CDN https://unpkg.com/phosphor-icons and try using the phosphor icons.

I am getting below when I tried opening the CDN link https://unpkg.com/phosphor-icons in browser
![image](https://user-images.githubusercontent.com/85510959/198610705-a05279ad-c92e-4a6e-b931-adf7e0b0ec0c.png)

**Comment by adavidson21** [comment]
Adding this here since I ran across this issue today - unkpg seems to be a bit unreliable (mjackson/unpkg#343), you can use an alternative like [jsdelivr](https://www.jsdelivr.com/unpkg) as a more reliable CDN instead. 

Using jsdelivr, you can use https://cdn.jsdelivr.net/npm/@phosphor-icons/web in place of https://unpkg.com/phosphor-icons
