### ISSUE TITLE
Duotone ArrowLeft and ArrowRight wrong visuals

### ISSUE THREAD

**Issue by jmfantin2** [phosphor-icons/homepage#314]
**Describe the bug**

When rendering duotone **ArrowLeft** and **ArrowRight** they come **open**, as in "directed association", and not closed, as in "inheritance" - the way it's expected to be in https://phosphoricons.com/ (i'm talking Class Diagram language so you can read what i mean)

![image](https://github.com/phosphor-icons/homepage/assets/11260509/68c876ae-44f5-4dc4-9a1b-8a183cd488fd)

**To Reproduce**

1. Find `arrow-left` and `arrow-right` in the Phosphor Icons library.
2. Set to duotone and copy the given React code.
3. Render it in the app after importing ArrowLeft and ArrowRight from "phosphor-react"

**Expected behavior**

_It's interesting to point out that ArrowCircleLeft and ArrowCircleRight work just as expected._ And for that reason I believe there's something going on with ArrowLeft and ArrowRight. 

![image](https://github.com/phosphor-icons/homepage/assets/11260509/59bae5e2-33f8-49ca-a651-3fa41c5d554d) ![image](https://github.com/phosphor-icons/homepage/assets/11260509/b718df18-121a-4d2b-99da-579ea9d22719)

**Screenshots**

![image](https://github.com/phosphor-icons/homepage/assets/11260509/e80cd161-3441-4ed4-aa31-3107d114b3e4)

Lastly, THANK YOU for this amazing library. I'm only doing this for the designers :)

**Comment by rektdeckard** [comment]
Hi @jmfantin2. In previous versions there were a number of incomplete duotone implementations, especially for line-like icons. We've fixed this in the [2.0 release](https://github.com/phosphor-icons/homepage/releases/tag/v2.0.0), so you should see the expected behavior if you upgrade to >=2.0.0. This package is now under our new namespace on NPM, so you will need to replace `phosphor-react` with `@phosphor-icons/react`.

If you have any more questions specific to the react lib, please make an issue [over there](https://github.com/phosphor-icons/react)!
