### ISSUE TITLE
Wrong Discord icon

### ISSUE THREAD

**Issue by audn** [phosphor-icons/homepage#371]
I don't think this is what the Discord icon is supposed to look like?

<img width="463" alt="image" src="https://github.com/phosphor-icons/homepage/assets/21041399/688eaccb-dc9a-4820-8a66-7064284ed96b">

From [Phospor Icons ](https://phosphoricons.com/)

Discord Logo
<img width="253" alt="image" src="https://github.com/phosphor-icons/homepage/assets/21041399/9348ffb8-d4fd-48c4-8d3d-caf9db920449">
From [Discord's Branding](https://discord.com/branding)

**Comment by iv-stpn** [comment]
I am developing a platform where different social medias are used and I am having to create a special case when displaying Discord's logo instead of using the one provided by phosphor icons, because it looks too out of place

An update would be important and save time/code for people in the same situation as me!

Here is a [filled](https://www.svgrepo.com/svg/506463/discord) and [regular](https://www.svgrepo.com/svg/504277/discord) variant. I haven't found a CONTRIBUTING.md and am not sure how to do a proper PR or how to create duotone/thin versions, otherwise I would :)

At any rate, thanks for the great library @rektdeckard :raised_hands:

**Comment by rektdeckard** [comment]
Phosphor brand icons are stylized to match *our* brand aesthetics as much as possible, while still remaining faithful to the original. This is complicated, but it is also the reason we recommend using official brand assets, not Phosphor brand icons, in almost all cases. Please #392 for more info on our general approach to brand icons.

**Comment by rektdeckard** [comment]
@iv-stpn while we do accept code contributions and bug fixes, we do not generally accept design contributions in the form of icons. I'll work on writing an official contributing doc in the near future to clarify this!
