### ISSUE TITLE
Latest release has no assets?

### ISSUE THREAD

**Issue by CodeDoctorDE** [phosphor-icons/homepage#457]
**Describe the bug**

The 2.0.0 release had a zip containing all icons.

**Steps to Reproduce**

Go to the latest 2.1.0 release

**Expected behavior**

Having a .zip asset

**Screenshots**

**Context (please complete the following information):**

**Additional notes**

**Comment by rektdeckard** [comment]
You're right! It has now been added.

**Comment by CodeDoctorDE** [comment]
Hmm, the zips are not consistent, the flutter generator searches for a version folder inside it.
Maybe we can automate this? Where is the script that creates this zip?

**Comment by rektdeckard** [comment]
It's just a few shell commands I run myself, no script. I could certainly make it a Github workflow, but it would mean I'd need to push, wait for actions to finish, then pull in order to get the site updated via FTP.

Wasn't aware flutter script was depending on the filename. 2.0 was in fact the exception, all other zips have been a single folder named "phosphor-icons". It should continue to be that way in the future.

**Comment by CodeDoctorDE** [comment]
Oh okay,
You could also change the site with github actions and we could add the script as a github workflow that runs when you publish the release.
> Wasn't aware flutter script was depending on the filename. 2.0 was in fact the exception, all other zips have been a single folder named "phosphor-icons". It should continue to be that way in the future.

Yeah, then I would change it in the pr that I created on the flutter phosphor repo.
