### ISSUE TITLE
White Plus / Minus Icon are not white on dark background color

### ISSUE THREAD

**Issue by bastiW** [phosphor-icons/homepage#458]
**Describe the bug**

Some white Icons appeal differently on some font sizes on dark background colour. It looks more light blue or grey. 
I noticed it on the plus and minus icon.

**Steps to Reproduce**

Reproduction Link: https://stackblitz.com/edit/vitejs-vite-kvithz?file=src%2FApp.tsx,src%2FApp.css,src%2Findex.css&terminal=dev
Zoom in and out and have a look at the plus and minus. 

**Expected behaviour**

Plus and Minus icon should be white no matter which zoom / dpi / size level. 

**Screenshots**

![image](https://github.com/phosphor-icons/homepage/assets/7667003/b2f75462-9b5b-482d-b3c3-be59e1b38db0)

**Context**

- OS: Windows 10
- Browser/Environment [Chrome, safari, node]
- Library  @phosphor-icons/react (I also had the issue with Angular)
- Version 2.1.4

**Additional notes**
This might also affect other icons.

**Comment by rektdeckard** [comment]
Unfortunately, this is caused by subpixel rendering native to your platform, and is a side-effect of the fact that we do not pixel-snap our icons. This is prohibitive for a general-purpose icon set that is meant to be used at many sizes, and not something we will change.

YMMV, but the best outcome is either to use the icons at 16px of multiples of it, or to *with great care* apply the `shape-rendering: crispedges;` CSS property (this can cause a lot of ugliness in shapes with curves and diagonals).
