### ISSUE TITLE
Documentation lacks requiring 'ph' class

### ISSUE THREAD

**Issue by rienheuver** [phosphor-icons/homepage#582]
**Describe the bug**

The documentation describes using the icons with, for example, `<i class="ph-smiley"></i>`, but that didn't work for me. It misses the extra `ph` class, so `<i class="ph ph-smiley"></i>` does work.

**Steps to Reproduce**

Include the script or style tag as per the web installation instructions in the `<head>` tag:
```
<script src="https://unpkg.com/@phosphor-icons/web"></script>
OR
<link rel="stylesheet" type="text/css" href="https://unpkg.com/@phosphor-icons/web@2.1.1/src/regular/style.css" />
```
Try an icon as per the documentation: `<i class="ph-smiley"></i>`

**Expected behavior**

An smiley icon appears on your page

**Additional notes**

1. I don't think that the current documentation is possible either, at least I don't yet see a way to make it work without the extra `ph` class.
2. Unless you're willing to slightly change the usage into `<i class="ph">smiley</i>`, which is the syntax Google's [material icons](https://developers.google.com/fonts/docs/material_icons) uses.
3. Let me know if I can help out with a PR for example.
4. The getting started of @phosphor-icons/homepage mentions installation of the `<script>` tag whereas @phosphor-icons/web recommends using the `<style>` tag. Perhaps worthwhile streamling that.

**Comment by rienheuver** [comment]
Just accidentally found out that the material-icons syntax (which I prefer) is already supported. So the docs could also be updated to show `<i class="ph">smiley</i>`. Again, please let me know if I should make this into a PR for this and/or the web repo's

**Comment by rektdeckard** [comment]
There was one missing `ph` class in the example in the docs here, [which is now fixed](https://github.com/phosphor-icons/homepage/commit/710518cdaaf5dd2da42b9247c35b137a56735bf9). The official documentation for this package already appears to be correct: [@phosphor-icons/web](https://github.com/phosphor-icons/web).

Regarding your last point, the demo on *this* readme shows us using the `<script>` tag because it is the simplest way to get all the weights loaded. The official docs [go into detail](https://github.com/phosphor-icons/web?tab=readme-ov-file#weights) about which to use and when.
