### ISSUE TITLE
Icons disappeared

### ISSUE THREAD

**Issue by msfoxett** [phosphor-icons/homepage#657]
**Describe the bug**

Icons are not loading/showing

**Steps to Reproduce**

I have 2 places that I use these icons and they are not populating

**Expected behavior**

I expect them to show up

**Screenshots**

![image](https://github.com/user-attachments/assets/82afa46b-c953-4e8c-a60b-8a2b6e1de2ec)

The blank spaces are where the icons usually populate as links.

**Context (please complete the following information):**

**Additional notes**

**Comment by danielganea** [comment]
I also have the same issue where the icons are not showing

**Comment by msfoxett** [comment]
I was informed that switching out from

<script src="https://unpkg.com/@phosphor-icons/web"></script>

to

<script src="https://unpkg.com/@phosphor-icons/web@2.1.1"></script>

Seems to have fixed the issue

**Comment by rektdeckard** [comment]
@msfoxett this is a result of a different version of the icon font being loaded in your page – either icon names or the unicode codepoints they are represented by have changed between versions. In general you should always pin phosphor to a specific version number to keep this from happening, and to take advantage of a single version being cached in the user's browser and therefore loading much faster.

Since `v2.1.0` we have stabilized the codepoints so they won't change, meaning future versions will be backwards-compatible with the current version. But I still recommend choosing a version explicitly, and checking the icons whenever you make an upgrade. I'll update the README here to reflect this.
